name: Build

on: pull_request

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - name: Install packages
        run: npm install
      - name: Build project
        run: npm run build
